/*
ENV API

Description of the ENV API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package env

import (
	"encoding/json"
)

// checks if the OrganizationsOrgIdClientsClientIdGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationsOrgIdClientsClientIdGet200Response{}

// OrganizationsOrgIdClientsClientIdGet200Response struct for OrganizationsOrgIdClientsClientIdGet200Response
type OrganizationsOrgIdClientsClientIdGet200Response struct {
	ClientId *string `json:"client_id,omitempty"`
	ClientSecret *string `json:"client_secret,omitempty"`
	Name *string `json:"name,omitempty"`
	OrgId *string `json:"org_id,omitempty"`
	UserId *string `json:"user_id,omitempty"`
	GrantTypes []string `json:"grant_types,omitempty"`
}

// NewOrganizationsOrgIdClientsClientIdGet200Response instantiates a new OrganizationsOrgIdClientsClientIdGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationsOrgIdClientsClientIdGet200Response() *OrganizationsOrgIdClientsClientIdGet200Response {
	this := OrganizationsOrgIdClientsClientIdGet200Response{}
	return &this
}

// NewOrganizationsOrgIdClientsClientIdGet200ResponseWithDefaults instantiates a new OrganizationsOrgIdClientsClientIdGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationsOrgIdClientsClientIdGet200ResponseWithDefaults() *OrganizationsOrgIdClientsClientIdGet200Response {
	this := OrganizationsOrgIdClientsClientIdGet200Response{}
	return &this
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *OrganizationsOrgIdClientsClientIdGet200Response) GetClientId() string {
	if o == nil || IsNil(o.ClientId) {
		var ret string
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationsOrgIdClientsClientIdGet200Response) GetClientIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *OrganizationsOrgIdClientsClientIdGet200Response) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given string and assigns it to the ClientId field.
func (o *OrganizationsOrgIdClientsClientIdGet200Response) SetClientId(v string) {
	o.ClientId = &v
}

// GetClientSecret returns the ClientSecret field value if set, zero value otherwise.
func (o *OrganizationsOrgIdClientsClientIdGet200Response) GetClientSecret() string {
	if o == nil || IsNil(o.ClientSecret) {
		var ret string
		return ret
	}
	return *o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationsOrgIdClientsClientIdGet200Response) GetClientSecretOk() (*string, bool) {
	if o == nil || IsNil(o.ClientSecret) {
		return nil, false
	}
	return o.ClientSecret, true
}

// HasClientSecret returns a boolean if a field has been set.
func (o *OrganizationsOrgIdClientsClientIdGet200Response) HasClientSecret() bool {
	if o != nil && !IsNil(o.ClientSecret) {
		return true
	}

	return false
}

// SetClientSecret gets a reference to the given string and assigns it to the ClientSecret field.
func (o *OrganizationsOrgIdClientsClientIdGet200Response) SetClientSecret(v string) {
	o.ClientSecret = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *OrganizationsOrgIdClientsClientIdGet200Response) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationsOrgIdClientsClientIdGet200Response) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *OrganizationsOrgIdClientsClientIdGet200Response) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *OrganizationsOrgIdClientsClientIdGet200Response) SetName(v string) {
	o.Name = &v
}

// GetOrgId returns the OrgId field value if set, zero value otherwise.
func (o *OrganizationsOrgIdClientsClientIdGet200Response) GetOrgId() string {
	if o == nil || IsNil(o.OrgId) {
		var ret string
		return ret
	}
	return *o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationsOrgIdClientsClientIdGet200Response) GetOrgIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrgId) {
		return nil, false
	}
	return o.OrgId, true
}

// HasOrgId returns a boolean if a field has been set.
func (o *OrganizationsOrgIdClientsClientIdGet200Response) HasOrgId() bool {
	if o != nil && !IsNil(o.OrgId) {
		return true
	}

	return false
}

// SetOrgId gets a reference to the given string and assigns it to the OrgId field.
func (o *OrganizationsOrgIdClientsClientIdGet200Response) SetOrgId(v string) {
	o.OrgId = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *OrganizationsOrgIdClientsClientIdGet200Response) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationsOrgIdClientsClientIdGet200Response) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *OrganizationsOrgIdClientsClientIdGet200Response) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *OrganizationsOrgIdClientsClientIdGet200Response) SetUserId(v string) {
	o.UserId = &v
}

// GetGrantTypes returns the GrantTypes field value if set, zero value otherwise.
func (o *OrganizationsOrgIdClientsClientIdGet200Response) GetGrantTypes() []string {
	if o == nil || IsNil(o.GrantTypes) {
		var ret []string
		return ret
	}
	return o.GrantTypes
}

// GetGrantTypesOk returns a tuple with the GrantTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationsOrgIdClientsClientIdGet200Response) GetGrantTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.GrantTypes) {
		return nil, false
	}
	return o.GrantTypes, true
}

// HasGrantTypes returns a boolean if a field has been set.
func (o *OrganizationsOrgIdClientsClientIdGet200Response) HasGrantTypes() bool {
	if o != nil && !IsNil(o.GrantTypes) {
		return true
	}

	return false
}

// SetGrantTypes gets a reference to the given []string and assigns it to the GrantTypes field.
func (o *OrganizationsOrgIdClientsClientIdGet200Response) SetGrantTypes(v []string) {
	o.GrantTypes = v
}

func (o OrganizationsOrgIdClientsClientIdGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationsOrgIdClientsClientIdGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ClientId) {
		toSerialize["client_id"] = o.ClientId
	}
	if !IsNil(o.ClientSecret) {
		toSerialize["client_secret"] = o.ClientSecret
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.OrgId) {
		toSerialize["org_id"] = o.OrgId
	}
	if !IsNil(o.UserId) {
		toSerialize["user_id"] = o.UserId
	}
	if !IsNil(o.GrantTypes) {
		toSerialize["grant_types"] = o.GrantTypes
	}
	return toSerialize, nil
}

type NullableOrganizationsOrgIdClientsClientIdGet200Response struct {
	value *OrganizationsOrgIdClientsClientIdGet200Response
	isSet bool
}

func (v NullableOrganizationsOrgIdClientsClientIdGet200Response) Get() *OrganizationsOrgIdClientsClientIdGet200Response {
	return v.value
}

func (v *NullableOrganizationsOrgIdClientsClientIdGet200Response) Set(val *OrganizationsOrgIdClientsClientIdGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationsOrgIdClientsClientIdGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationsOrgIdClientsClientIdGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationsOrgIdClientsClientIdGet200Response(val *OrganizationsOrgIdClientsClientIdGet200Response) *NullableOrganizationsOrgIdClientsClientIdGet200Response {
	return &NullableOrganizationsOrgIdClientsClientIdGet200Response{value: val, isSet: true}
}

func (v NullableOrganizationsOrgIdClientsClientIdGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationsOrgIdClientsClientIdGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


